fitnesstracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('exercise_search/<int:routine_id>/',
         views.exercise_search, name='exercise_search'),
    path('accounts/signup/', views.signup, name='signup'),
    path('add_routine/', views.add_routine, name='add_routine'),
    path('view_routines/', views.view_routines, name='view_routines'),
    path('add_exercise/<int:routine_id>/<int:exercise_id>/',
         views.add_exercise, name='add_exercise'),
    path('delete_routine/<int:routine_id>',
         views.delete_routine, name='delete_routine'),
    path('delete_exercise/<int:routine_id>/<int:exercise_id>',
         views.delete_exercise, name='delete_exercise'),

]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Exercise(models.Model):
    api_id = models.IntegerField(null=True, default=None)
    name = models.CharField(max_length=200)
    description = models.TextField()
    muscle_group = models.CharField(max_length=200)
    image_url = models.URLField()

    def __str__(self):
        return self.name


class TrainingDay(models.Model):
    DAY_CHOICES = (
        ('Mon', 'Monday'),
        ('Tue', 'Tuesday'),
        ('Wed', 'Wednesday'),
        ('Thu', 'Thursday'),
        ('Fri', 'Friday'),
        ('Sat', 'Saturday'),
        ('Sun', 'Sunday')
    )

    day = models.CharField(max_length=3, choices=DAY_CHOICES)

    def __str__(self):
        return self.day


class Routine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    days_of_week = models.ManyToManyField(TrainingDay)

    def __str__(self):
        return f'Routine {self.name} for {self.user.username}'


class PlannedExercise(models.Model):
    routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    sets = models.IntegerField()
    reps = models.IntegerField()

    def __str__(self):
        return f'Planned exercise in routine {self.routine}'


class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    date = models.DateField()
    sets = models.IntegerField(default=0)
    reps = models.IntegerField(default=0)
    weight = models.FloatField(default=0.0)

    def __str__(self):
        return f'Log for {self.user.username} on {self.date}'

main_app/forms.py
from django import forms
from .models import Routine, PlannedExercise


class RoutineForm(forms.ModelForm):
    class Meta:
        model = Routine
        fields = ['name', 'days_of_week']
        widgets = {
            'days_of_week': forms.SelectMultiple(attrs={'class': 'browser-default'})
        }


class PlannedExerciseForm(forms.ModelForm):
    class Meta:
        model = PlannedExercise
        fields = ['sets', 'reps']

main_app/views.py
from django.contrib import messages
import requests
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth import login
from .forms import RoutineForm, PlannedExerciseForm
from .models import TrainingDay, Routine, Exercise, PlannedExercise

# Create your views here.


@login_required
def home(request):
    days_of_week = TrainingDay.objects.all()
    routines = Routine.objects.filter(user=request.user)
    return render(request, 'main_app/home.html', {'days_of_week': days_of_week, 'routines': routines})


def signup(request):
    # POST request
    error_message = ''
    # user is signing up with a form submission
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'invalid signup - try again'
    # GET request
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form,
        'error': error_message
    })
    # user is navigating to signup page to fill out the form


@login_required
def view_routines(request):
    routines = Routine.objects.filter(user=request.user)
    return render(request, 'main_app/view_routines.html', {'routines': routines})


@login_required
def add_routine(request):
    if request.method == 'POST':
        form = RoutineForm(request.POST)
        if form.is_valid():
            selected_days = form.cleaned_data.get('days_of_week')
            # Check if routine already exists for selected days
            for day in selected_days:
                if Routine.objects.filter(user=request.user, days_of_week=day).exists():
                    messages.error(
                        request, f'Routine already exists for {day}.')
                    # or render the form again with an error message
                    return redirect('add_routine')
            # Save the routine if no conflicts
            routine = form.save(commit=False)
            routine.user = request.user
            routine.save()
            form.save_m2m()  # save the many-to-many relationship with TrainingDay
            return redirect('home')
    else:
        form = RoutineForm()
    return render(request, 'main_app/add_routine.html', {'form': form})


@login_required
def add_exercise(request, routine_id, exercise_id):
    routine = get_object_or_404(Routine, id=routine_id)
    selected_exercise = get_object_or_404(Exercise, id=exercise_id)
    if request.method == 'POST':
        form = PlannedExerciseForm(request.POST)
        if form.is_valid():
            planned_exercise = form.save(commit=False)
            planned_exercise.routine = routine
            planned_exercise.exercise = selected_exercise
            planned_exercise.save()
            return redirect('view_routines')
    else:
        # Set initial data for the form
        form = PlannedExerciseForm(initial={'exercise': selected_exercise})
    return render(request, 'main_app/add_exercise.html', {'form': form, 'routine': routine, 'selected_exercise': selected_exercise, 'selected_exercise_id': exercise_id})


@login_required
def exercise_search(request, routine_id):
    query = request.GET.get('query')
    exercises = []
    if query:
        exercises = Exercise.objects.filter(name__icontains=query)
    return render(request, 'main_app/exercise_search.html', {'exercises': exercises, 'routine_id': routine_id})


@require_http_methods(["POST"])
def delete_routine(request, routine_id):
    try:
        routine = Routine.objects.get(pk=routine_id)
        routine.delete()
    except Routine.DoesNotExist:
        pass  # handle the case where the routine does not exist if needed
    return redirect('view_routines')


@require_http_methods(["POST"])
def delete_exercise(request, routine_id, exercise_id):
    try:
        planned_exercise = PlannedExercise.objects.get(
            pk=exercise_id, routine__id=routine_id)
        planned_exercise.delete()
    except PlannedExercise.DoesNotExist:
        pass
    return redirect('view_routines')

main_app/templates/main_app/add_exercise.html
{% extends 'main_app/base.html' %}

{% load widget_tweaks %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card-panel">
                <h4 class="center-align">Add Exercise to {{ routine.name }}</h4>
                <form method="post" action="{% url 'add_exercise' routine.id selected_exercise.id %}">
                    {% csrf_token %}
                    <div class="input-field">
                        {{ form.exercise|add_class:"browser-default" }}
                    </div>
                    <div class="input-field">
                        <label for="{{ form.sets.id_for_label }}">Sets:</label>
                        {{ form.sets|add_class:"validate" }}
                    </div>
                    <div class="input-field">
                        <label for="{{ form.reps.id_for_label }}">Reps:</label>
                        {{ form.reps|add_class:"validate" }}
                    </div>
                    <div class="center-align">
                        <button type="submit" class="btn waves-effect waves-light">Add Exercise</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/add_routine.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col s12">
            <h3 class="center-align">Add Routine</h3>
            <div class="card">
                <div class="card-content">
                    <form method="post" action="{% url 'add_routine' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                            <i class="material-icons right">send</i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
    });
</script>
{% endblock %}

main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>FitTrax</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <a href="/" class="left brand-logo" style="padding-left: 20px;">FitTrax</a>
                <ul class="right" style="padding-right: 20px;">
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        <li><a href="{% url 'view_routines' %}">View Routines</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container" style="padding-top: 30px;">{% block content %}{% endblock %}</main>
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, &copy; 2023 FitTrax &nbsp;
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    {% block script %}{% endblock %}
</body>
</html>

main_app/templates/main_app/exercise_search.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="container">
    <h3>Search for Exercises</h3>
    <form method="get" action="{% url 'exercise_search' routine_id %}">
        <input type="text" name="query" placeholder="Search...">
        <button type="submit" class="btn">Search</button>
    </form>
    
    <ul>
        {% for exercise in exercises %}
        <li>
            <a href="{% url 'add_exercise' routine_id exercise.id %}">{{ exercise.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

main_app/templates/main_app/home.html
{% extends 'main_app/base.html' %} 
{% block content %}

<div class="row">
    <div class="col s12">
        <div class="card z-depth-3">
            <div class="card-content center-align">
                <h4>Motivational Quote of the Day</h4>
                <p id="quote-text" class="flow-text"></p>
                <p><strong>- <span id="quote-author"></span></strong></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col s12">
        <div class="card z-depth-3">
            <div class="card-content">
                <span class="card-title center-align">My Routines</span>
                <table class="striped centered">
                    <thead>
                        <tr>
                            <th>Day of the Week</th>
                            <th>Routine</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for day in days_of_week %}
                        <tr>
                            <td>{{ day.day }}</td>
                            <td>
                                {% for routine in routines %}
                                    {% for routine_day in routine.days_of_week.all %}
                                        {% if routine_day.day == day.day %}
                                            <span class="routine-name">{{ routine.name }}</span>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </td>
                            <td>
                                {% for routine in routines %}
                                    {% for routine_day in routine.days_of_week.all %}
                                        {% if routine_day.day == day.day %}
                                            <form style="display:inline;" method="post" action="{% url 'delete_routine' routine.id %}">
                                                {% csrf_token %}
                                                <button type="submit" class="btn-flat delete-routine-btn"><i class="material-icons">delete</i></button>
                                            </form>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-action center-align">
                <a class="waves-effect waves-light btn" href="{% url 'add_routine' %}">
                    <i class="material-icons left">add</i>Add Routine
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        // Fetch motivational quote
        const settings = {
            "async": true,
            "crossDomain": true,
            "url": "https://type.fit/api/quotes",
            "method": "GET"
        }

        $.ajax(settings).done(function (response) {
            const data = JSON.parse(response);
            // Select a random quote from the array
            const randomIndex = Math.floor(Math.random() * data.length);
            const quote = data[randomIndex];
            // Update the HTML content with the quote
            $("#quote-text").text(quote.text);
            $("#quote-author").text(quote.author || 'Unknown');
        });
    });
</script>
{% endblock %}

main_app/templates/main_app/view_routines.html
{% extends 'main_app/base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <h3 class="center-align">My Routines</h3>

        {% for routine in routines %}
            <div class="col s12 m6">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            {{ routine.name }}
                        </span>
                        <p>Days: {{ routine.days_of_week.all|join:", " }}</p>
                        <ul>
                            {% for planned_exercise in routine.plannedexercise_set.all %}
                                <li>
                                    {{ planned_exercise.exercise.name }}: {{ planned_exercise.sets }} x {{ planned_exercise.reps }}
                                    <form style="display:inline;" method="post" action="{% url 'delete_exercise' routine.id planned_exercise.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn-flat delete-exercise-btn"><i class="material-icons">delete</i></button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'exercise_search' routine.id %}">Add Exercises</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col s12">
                <p class="center-align">You have no routines yet. <a href="{% url 'add_routine' %}">Add one now!</a></p>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}